### ISSUE TITLE
Which flags to use with installr?

### ISSUE THREAD

**Issue by officialpatterson** [r-hub/r-minimal#32]
Hi everyone,

I want to install a package using `installr` but I'm not sure what flags to use - I don't know whether I want to keep the c++/alpine packages temporarily or permanently for a package. Is there a way to only keep what's necessary?

Take the shiny example that's been provided.
```
FROM rhub/r-minimal

RUN apk add --no-cache --update-cache \
        --repository http://nl.alpinelinux.org/alpine/v3.11/main \
        autoconf=2.69-r2 \
        automake=1.16.1-r0 && \
    # repeat autoconf and automake (under `-t`)
    # to (auto)remove them after installation
    installr -d \
        -t "bash libsodium-dev curl-dev linux-headers autoconf automake" \
        -a libsodium \
        shiny
```
How is it `bash libsodium-dev curl-dev linux-headers autoconf automake` were known to be needed only temporarily but `libsodium` was known to be needed permanently?

Thanks in advance!

**Comment by gaborcsardi** [comment]
This is a great question. In general, you need to know a bit more about the dependencies to decide, and sometimes it is also a bit of trial and error. Luckily, there are some clues.

On Alpine Linux, most libraries come in two packages, the runtime package, and the compile-time, or dev-package. The latter has `-dev` suffix. E.g. `libsodium` is needed for _running_ code that links to libsodium, like the `sodium` R package. `libsodium-dev` is needed for _compiling_ the code that uses libsodium. So for the shiny case, `libsodium` is needed after the installation, but `libsodium-dev` is not.

Other Alpine packages that are not libraries are a bit harder to guess. What usually happens is that the installation does not work without those packages, and then you add them until the installation works. These packages are often not specified in the `SystemRequirements` of the R packages, because they are present on most Unix systems. E.g. `bash` is such. But we are trying to make small containers here, so often they are not present on `r-minimal`.

If you are unsure if a package can be removed after installation, then you can just keep it. It will make the container bigger, but usually not much bigger. E.g. keeping `bash` for the shiny container would be probably fine. 

We are planning to make this process easier and automate the installation of compile-time and run-time system packages, but this will probably only happen next year.

Lastly, you can always ask here, if you really need a minimal container and you are not sure what you can remove.

**Comment by gaborcsardi** [comment]
I hope my answer above helped a bit. Please open issues if you have more questions.
